Repository devcourse-mongsang/mongsang, pull requests merged in 2025-01, with the labels that each got.

#2 🎉 kickoff: yarn 기반 초기 vue 프로젝트 파일 빌드
  .gitignore
  README.md
  index.html
  jsconfig.json
  package.json
  postcss.config.js
  public/favicon.ico
  src/App.vue
  src/assets/css/index.css
  src/assets/css/tailwind.css
  src/components/HelloWorld.vue
  src/components/TheWelcome.vue
  src/components/WelcomeItem.vue
  src/components/icons/IconCommunity.vue
  src/components/icons/IconDocumentation.vue
  src/components/icons/IconEcosystem.vue
  src/components/icons/IconSupport.vue
  src/components/icons/IconTooling.vue
  src/main.js
  tailwind.config.js
  vite.config.js
  yarn.lock
Labels: documentation

#3 [merge / dev] merge project file for CI/CD
  .gitignore
  README.md
  index.html
  jsconfig.json
  package.json
  postcss.config.js
  public/favicon.ico
  src/App.vue
  src/assets/css/index.css
  src/assets/css/tailwind.css
  src/components/HelloWorld.vue
  src/components/TheWelcome.vue
  src/components/WelcomeItem.vue
  src/components/icons/IconCommunity.vue
  src/components/icons/IconDocumentation.vue
  src/components/icons/IconEcosystem.vue
  src/components/icons/IconSupport.vue
  src/components/icons/IconTooling.vue
  src/main.js
  tailwind.config.js
  vite.config.js
  yarn.lock
Labels: documentation

#6 [merge / 4-setup-github-actions-for-cicd] ✨feat: ci/cd 초기설정
  .github/workflows/deploy-netlify.yml
Labels: enhancement

#7 [merge / dev] ✨feat: connect CI / CD pipeline with Nettlify
  .github/workflows/deploy-netlify.yml
Labels: enhancement

#8 [merge / 5-initialize-project-with-folder-structure-and-required-dependencies]🌱 Add: 필수 의존성 설치 및 초기 프로젝트 파일 구조 세팅
  README.md
  package.json
  src/App.vue
  src/components/HelloWorld.vue
  src/components/TheWelcome.vue
  src/components/WelcomeItem.vue
  src/components/icons/IconCommunity.vue
  src/components/icons/IconDocumentation.vue
  src/components/icons/IconEcosystem.vue
  src/components/icons/IconSupport.vue
  src/components/icons/IconTooling.vue
  src/main.js
  src/pages/Diary.vue
  src/pages/Home.vue
  src/pages/Record.vue
  src/router/index.js
  yarn.lock
Labels: enhancement

#9 [merge / dev] ✨feat: connect CI / CD pipeline with Nettlify_2
  README.md
  package.json
  src/App.vue
  src/components/HelloWorld.vue
  src/components/TheWelcome.vue
  src/components/WelcomeItem.vue
  src/components/icons/IconCommunity.vue
  src/components/icons/IconDocumentation.vue
  src/components/icons/IconEcosystem.vue
  src/components/icons/IconSupport.vue
  src/components/icons/IconTooling.vue
  src/main.js
  src/pages/Diary.vue
  src/pages/Home.vue
  src/pages/Record.vue
  src/router/index.js
  yarn.lock
Labels: documentation

#10 📝docs: 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/bug-report-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
Labels: documentation

#12 [merge / 20-setup-github-settings] 📝docs: PR 템플릿 수정
  pull_request_template.md
Labels: documentation

#16 ✨ Feat: 사이드바 세부 요소 구현, 드롭다운 메뉴 애니메이션 추가
  public/assets/icons/arrow_down_icon.svg
  public/assets/icons/diary_icon.svg
  public/assets/icons/logout_icon.svg
  public/assets/icons/mode_toggle_icon.svg
  public/assets/icons/notification_active_icon.svg
  public/assets/icons/notification_icon.svg
  public/assets/icons/pencil_icon.svg
  public/assets/icons/people_icon.svg
  public/assets/icons/sidebar_hr.svg
  src/components/common/DropDownCommunity.vue
  src/components/common/Sidebar.vue
Labels: documentation

#18 [merge / 17-bug-modify_sidebar_icons] ✨ Feat: 사이드바 mui icons 적용, 랜딩 페이지 반응형 디자인 적용
  package.json
  src/components/common/DropDownCommunity.vue
  src/components/common/Headers.vue
  src/components/common/Sidebar.vue
  src/layouts/LayoutMain.vue
  src/pages/Home.vue
  src/store/sidebar.js
  tailwind.config.js
  yarn.lock
Labels: bug, enhancement

#22 [merge / 21-add-tailwind-custom-colors] 📝 docs: Tailwind에 사용자 정의 색상 추가
  tailwind.config.js
Labels: documentation

#27 [merge / 26-input-component-ui] ✨ input 컴포넌트 구현
  src/components/common/Input.vue
  tailwind.config.js
Labels: enhancement

#29 [merge / 28-button-component-ui] ✨ Button 컴포넌트 구현
  index.html
  src/components/common/Button.vue
Labels: enhancement

#30 [merge / 25-feat-community-board-detail-ui]✨ Feat: 커뮤니티 게시물 상세페이지 구현
  public/assets/imgs/img_placeholder.png
  src/components/common/Button.vue
  src/components/common/DropDown.vue
  src/components/common/DropDownCommunity.vue
  src/components/common/Sidebar.vue
  src/components/custom-hook/PostItem.vue
  src/layouts/LayoutCommunity.vue
  src/mock-db/boardData.json
  src/pages/community-pages/CommunityBoard.vue
  src/pages/community-pages/DreamInterpretation.vue
  src/pages/community-pages/FreeBoard.vue
  src/pages/community-pages/GoodDream.vue
  src/pages/community-pages/LucidDream.vue
  src/pages/community-pages/Nightmare.vue
  src/pages/community-pages/PostDetails.vue
  src/pages/community-pages/PropheticDream.vue
  src/pages/community-pages/RecurrentDream.vue
  src/pages/community-pages/SurrealDream.vue
  src/router/index.js
  src/utils/dateConveter.js
Labels: enhancement

#32 [merge / 23-mypage-ui] ✨ Feat: 마이페이지 구현
  public/assets/imgs/unknownUser.png
  src/pages/my-pages/Profile.vue
Labels: enhancement

#36 [merge / 20-login-page-ui] ✨ 로그인 페이지 퍼블리싱
  public/assets/imgs/github_logo.png
  public/assets/imgs/google_logo.png
  public/assets/imgs/kakao_logo.png
  src/components/common/Button.vue
  src/components/common/Input.vue
  src/pages/Login.vue
  src/router/index.js
Labels: enhancement

#38 [merge / 37-join-page-ui] ✨ feat: 회원가입 페이지 퍼블리싱
  src/pages/Join.vue
Labels: enhancement

#40 [merge / 39-not-found-page] ✨ feat: 404 not found 페이지 구현
  public/assets/imgs/bg_not_found_desktop.png
  public/assets/imgs/bg_not_found_mobile.png
  src/pages/NotFound.vue
Labels: enhancement

#41 [merge / 35-sidebar-flexible-ui] 💄 style: 사이드바 모바일 반응형 적용
  src/components/common/DropDownCommunity.vue
  src/components/common/Sidebar.vue
  tailwind.config.js
Labels: enhancement

#44 [merge / 43-not-found-page-ui] 🐛 fix: 404 not found 페이지 화면 비율 조정 시 배경 반복되는 오류 해결
  src/pages/NotFound.vue
Labels: bug

#47 [merge / 46-supabase-initial-settings] ✨ feat: supabase 초기 세팅 완료
  .github/workflows/deploy-netlify.yml
  package.json
  src/config/supabase.js
  yarn.lock
Labels: enhancement

#48 [merge / 33-mypage-edit-ui] ✨ Feat: 마이페이지의 프로필 편집 페이지 구현
  src/components/common/Button.vue
  src/components/common/Input.vue
  src/pages/my-pages/Profile.vue
  src/pages/my-pages/ProfileEdit.vue
  src/router/index.js
Labels: enhancement

#53 [merge / 34-feat-community-post-list-mobile-ui-publishing] ✨ Feat: 커뮤니티 페이지 반응형 UI 퍼블리싱
  public/assets/imgs/bg_circle_mobile.png
  public/assets/imgs/bg_mobile.png
  src/components/common/CommunityChips.vue
  src/components/common/CoverflowSwiper.vue
  src/components/common/DropDown.vue
  src/components/common/Headers.vue
  src/layouts/LayoutCommunity.vue
  src/layouts/LayoutMain.vue
  src/pages/Home.vue
  src/pages/community-pages/CommunityBoard.vue
  src/pages/community-pages/PostDetails.vue
  src/router/index.js
  src/utils/dateConveter.js
Labels: enhancement

#54 [merge / 49-follow-page-ui] ✨ Feat: Friends & All users 페이지 구현
  src/pages/Follow.vue
  src/pages/my-pages/Profile.vue
  src/router/index.js
Labels: enhancement

#58 [merge / 45-record-page-ui] ✨ feat: 꿈기록 페이지 퍼블리싱
  public/assets/imgs/youtube_thumbnail.png
  src/components/common/Button.vue
  src/main.js
  src/pages/Record.vue
  tailwind.config.js
Labels: enhancement

#60 [merge / 59-vuetify-double-declared] 🐛 fix: vuetify 이중 선언 오류 해결
  src/main.js
Labels: bug

#63 [merge /62-problems-loading-email-login-data] 🐛 fix: login 매개변수 수정
  src/pages/Home.vue
  src/pages/Login.vue
Labels: bug

#65 [merge / 57-diary-detail-page-ui] ✨ feat: 일기장 상세 페이지 퍼블리싱
  public/assets/imgs/asmr.png
  public/assets/imgs/diary_logo.png
  src/layouts/LayoutMyPage.vue
  src/pages/diary-pages/Diary.vue
  src/pages/diary-pages/DiaryDetails.vue
  src/router/index.js
Labels: enhancement

#70 [merge / 66-create-modal-components] ✨ feat: 커스텀 모달창 구현
  src/App.vue
  src/components/common/Modal.vue
  src/store/modalStore.js
Labels: enhancement

#73 [merge / 71-implementation-of-membership-verification-errors] ✨ feat: 로그인, 회원가입 검증, 로그인 중일때 회원가입,로그인 페이지 접근 불가능 , input 컴포넌트 수정
  src/components/common/Input.vue
  src/pages/Join.vue
  src/pages/Login.vue
  src/pages/community-pages/PostDetails.vue
  src/router/index.js
Labels: enhancement

#78 [merge / 76-community-page-meatballs-menu] ✨ Feat: 커뮤니티 게시물 상세페이지 드롭다운 메뉴 구현
  src/components/common/MeatballsMenu.vue
  src/pages/community-pages/PostDetails.vue
Labels: enhancement

#81 [merge / 69-record-dream] ✨ feat: 꿈기록 작성 페이지 구현
  package.json
  src/pages/Record.vue
  vite.config.js
  yarn.lock
Labels: enhancement

#82 [merge / 75-implementing-modifying-my-page-profile] ✨ feat: 마이페이지 프로필 편집 구현
  src/pages/my-pages/ProfileEdit.vue
Labels: enhancement

#83 [merge / 67-diary-write-page-ui] ✨ feat: 일기장 작성 페이지 퍼블리싱 (미완)
  src/components/common/DatePicker.vue
  src/components/common/DropDownFace.vue
  src/components/common/DropDownWeather.vue
  src/pages/diary-pages/DiaryWrite.vue
  src/router/index.js
Labels: enhancement

#86 [merge / 80-community-image-modify-error] 🐛 Fix: 게시물 상세페이지 이미지 수정시 마운트된 미리보기 오류 해결
  src/api/api-community/imgsApi.js
  src/components/community/DragDropImg.vue
  src/pages/community-pages/CommunityBoard.vue
  src/pages/community-pages/CreatePost.vue
  src/pages/community-pages/PostDetails.vue
  src/pages/community-pages/UpdatePost.vue
  vite.config.js
Labels: bug

#89 [merge / 87-modal-component-modification]🐛 Fix: 모달창 폰트, 로그인, 회원가입 로직 수정
  src/components/common/Modal.vue
  src/pages/Join.vue
  src/pages/Login.vue
Labels: bug

#91 [merge / 88-add-loader-component] ✨ Feat: 커뮤니티 게시판 목록 페이지 skeleton UI 구현
  package.json
  src/components/community/SkeletonUi.vue
  src/pages/community-pages/CommunityBoard.vue
  src/pages/community-pages/PostDetails.vue
  src/pages/community-pages/UpdatePost.vue
  src/store/loadingStore.js
  yarn.lock
Labels: enhancement

#95 [merge / 94-record-diary-data-connect] ✨ feat: 꿈 기록 페이지와 일기장 작성 페이지의 데이터 연결, Pinia로 상태 관리
  src/pages/Record.vue
  src/pages/diary-pages/DiaryWrite.vue
  src/store/diaryStore.js
Labels: enhancement

#98 [merge / 84-sidebar-notification-data-connect] ✨Feat: 알림 페이지 퍼블리싱 & 알림 기능 구현
  src/components/common/Headers.vue
  src/components/common/Sidebar.vue
  src/pages/Notification.vue
  src/store/notificationsStore.js
Labels: enhancement

#100 [merge / 85-diary-data-connect] :sparkles: feat: write details page 데이…
  src/api/api-diary/api.js
  src/components/common/DropDownFace.vue
  src/components/common/DropDownWeather.vue
  src/pages/diary-pages/DiaryDetails.vue
  src/pages/diary-pages/DiaryWrite.vue
  src/router/index.js
Labels: enhancement

#102 [merge / 77-calender-data-connect] :sparkles: feat: 달력-상세 데이터 연동
  src/api/api-diary/api.js
  src/components/common/Calender.vue
Labels: enhancement

#104 [merge / 96-refactor-record-dream] ✨ feat: 반응형 구현 및 꿈 기록 페이지 리팩토링
  public/assets/imgs/youtube_placeholder.png
  src/pages/Record.vue
Labels: enhancement

#107 [merge / 90-user-page-connect] ✨ Feat: 유저 마이페이지, 팔로우 페이지 구현, 라우터 수정
  src/components/common/Button.vue
  src/pages/Follow.vue
  src/pages/Join.vue
  src/pages/my-pages/Profile.vue
  src/router/index.js
  src/store/followStore.js
Labels: enhancement

#110 [merge / 106-cannot-view-postitems]🐛 Fix: 로그인 하지 않았을 경우 게시물 상세페이지 내용을 열람할 수 없었던 에러 해결
  src/api/api-like/api.js
  src/components/common/LikesCounter.vue
  src/pages/community-pages/Comment.vue
  src/pages/community-pages/CommentList.vue
  src/pages/community-pages/PostDetails.vue
Labels: bug

#116 [merge / 108-implement-before-and-after-sidebar-login]✨ Feat: 사이드 바 로그인 회원 연동, 자기소개 16자 제한
  src/components/common/Input.vue
  src/components/common/Sidebar.vue
  src/pages/Follow.vue
  src/pages/Join.vue
  src/pages/my-pages/ProfileEdit.vue
Labels: enhancement

#114 [merge / 111-community-modal]✨ Feat: 로그인 하지 않고 일부 기능 접근 시도시 로그인 안내 모달 팝업 기능 구현 완료
  src/components/common/Headers.vue
  src/components/common/LikesCounter.vue
  src/pages/Home.vue
  src/pages/community-pages/Comment.vue
  src/pages/community-pages/CommunityBoard.vue
  src/pages/community-pages/PostDetails.vue
Labels: enhancement

#119 [merge / 118-calender-placeholder-ui] :bug: fix: 일기장 작성 여부에 따른 placeholder 교체
  public/assets/imgs/calender_placeholder.png
  src/components/common/Calender.vue
Labels: bug

#120 [merge / 115-community-sorting] ✨ Feat: 커뮤니티 목록 게시물 정렬 기능 구현 (최신순, 작성순, 좋아요순)
  src/api/api-like/api.js
  src/components/community/DropDownPostList.vue
  src/pages/community-pages/CommunityBoard.vue
  src/store/dropDownSortStore.js
  yarn.lock
Labels: enhancement

#122 [merge / 121-community-follow-btn] ✨ Feat: 커뮤니티 게시글 상세페이지 팔로우 버튼 활성화 완료
  src/api/api-follow/api.js
  src/pages/community-pages/CommentList.vue
  src/pages/community-pages/PostDetails.vue
Labels: enhancement

#123 [merge / 117-following-page-skeleton]✨ Feat: 팔로우 페이지 스켈레톤 구현
  src/components/community/SkeletonFollow.vue
  src/pages/Follow.vue
Labels: enhancement

#124 [merge / 113-fix-restrict-record-diary-button] 🐛 fix: 하루에 꿈 기록 페이지에서 일기 작성 페이지로 여러 번 이동 가능한 오류 해결
  index.html
  src/api/api-record/api.js
  src/pages/Record.vue
Labels: bug

#128 [merge / 103-diary-details-ui] :bug: fix: 매핑된 아이콘 불러오기와 상세에서 달력 바로가기
  src/pages/diary-pages/DiaryDetails.vue
  src/utils/iconUtils.js
Labels: bug

#126 [merge / 125-community-search-bar] ✨ Feat: 커뮤니티 게시물 목록 검색기능 구현 완료
  src/pages/community-pages/CommunityBoard.vue
Labels: enhancement

#136 [merge / 129-main-asmr-recommendation] ✨ feat: 홈 화면에 추천 asmr 영상 임베드
  src/pages/Home.vue
  src/pages/Record.vue
Labels: enhancement

#137 [merge / 135-problems-switching-profile-screens]🐛 fix: 다른 사용자 프로필 화면에서 내 프로필 화면으로 이동 오류 수정
  src/pages/my-pages/Profile.vue
Labels: bug

#138 [merge / 133-community-postlist-pagination] ✨ Feat: 커뮤니티 게시물 목록 pagination 기능 구현 완료
  package.json
  src/pages/community-pages/CommunityBoard.vue
  yarn.lock
Labels: enhancement

#140 [merge / 139-my-page-follow-error]🐛 fix: 마이페이지 팔로잉 오류 수정
  src/pages/Follow.vue
  src/pages/my-pages/Profile.vue
  src/pages/my-pages/ProfileEdit.vue
Labels: bug

#142 [merge / 141-reset-record-data] 🐛 fix: 꿈 기록 페이지의 데이터가 다른 페이지를 다녀와도 유지되는 오류 해결
  src/pages/Home.vue
  src/pages/Record.vue
  src/store/diaryStore.js
Labels: bug

#143 [merge / 130-diary-modal] :sparkles: feat: 일기수정/삭제기능 추가
  src/api/api-diary/api.js
  src/components/common/Calender.vue
  src/pages/diary-pages/DiaryDetails.vue
  src/pages/diary-pages/DiaryWrite.vue
  src/pages/diary-pages/UpdateDiary.vue
  src/router/index.js
Labels: enhancement

#146 [merge/144-diary-content] :bug: fix: 수정페이지 데이터 불러오기 오류 수정
  src/components/common/DropDownFace.vue
  src/components/common/DropDownWeather.vue
  src/pages/diary-pages/DiaryWrite.vue
Labels: bug

#147 [merge / 145-download-ai-image]✨ feat: AI 이미지 다운로드 구현
  src/pages/Record.vue
Labels: enhancement

#149 [merge / 132-notification-create] ✨ Feat: 알림 생성 기능 구현
  src/components/common/Headers.vue
  src/components/common/LikesCounter.vue
  src/pages/community-pages/Comment.vue
  src/pages/community-pages/PostDetails.vue
  src/store/followStore.js
Labels: enhancement

#153 [merge / 151-home-community-swiper-content] ✨ Feat: 홈 화면 실시간 인기글 데이터 연결 완료
  src/components/common/ HomeSwiperSkeletonUi.vue
  src/components/common/CoverflowSwiper.vue
Labels: enhancement

#155 [merge / 152-implementing-kakao-sharing] ✨ Feat: 카카오 공유하기 초안 완성
  index.html
  src/pages/community-pages/PostDetails.vue
Labels: enhancement

#158 [merge / 151-home-community-swiper-content] 🐛 Fix: 파일명 오타수정
  src/components/common/CoverflowSwiper.vue
  src/components/common/HomeSwiperSkeletonUi.vue
Labels: bug

#156 [merge / 150-follow-ui-rwd] ✨ Feat: 팔로잉&모든유저 목록 페이지 반응형 퍼블리싱
  src/pages/Follow.vue
Labels: enhancement

#160 [merge / 154-sidebar-click-event] 🐛 Fix: sidebar 외부 영역 클릭 이벤트 개선
  package.json
  src/components/common/Headers.vue
  src/components/common/Sidebar.vue
  src/store/sidebar.js
  yarn.lock
Labels: enhancement

#163 [merge / 162-deployment-test] 🐛 Fix: 배포를 위한 yml 파일 수정
  .github/workflows/deploy-netlify.yml
Labels: enhancement

#165 [merge/148-diary-calender-responsive-ui] :sparkles: feat:달력 반응형적용, 모달 디자인 통일
  src/components/common/Calender.vue
  src/pages/diary-pages/Diary.vue
  src/pages/diary-pages/DiaryDetails.vue
Labels: enhancement

#167 [merge / 166-correction-of-deployment-errors] 🐛 Fix: 배포 오류 수정
  .github/workflows/deploy-netlify.yml
  netlify.toml
  public/_redirects
  src/pages/Login.vue
  src/pages/community-pages/PostDetails.vue
Labels: enhancement

#168 [merge / 161-community-update-image] 🐛 Fix: 커뮤니티 게시글 수정시 이미지 데이터 소실되는 버그 해결
  src/api/api-community/imgsApi.js
  src/pages/community-pages/UpdatePost.vue
Labels: enhancement

#169 [merge / dev] deploy-mongsang-1.0.1
  .github/workflows/deploy-netlify.yml
  netlify.toml
  public/_redirects
  src/api/api-community/imgsApi.js
  src/components/common/Calender.vue
  src/pages/Login.vue
  src/pages/community-pages/PostDetails.vue
  src/pages/community-pages/UpdatePost.vue
  src/pages/diary-pages/Diary.vue
  src/pages/diary-pages/DiaryDetails.vue
Labels: enhancement

#170 [merge / 159-notification-follow-link]✨ Feat: 알림 follow 라우팅 수정
  src/pages/Notification.vue
Labels: enhancement

#174 [merge / 171-notification-logout-header-hidden] ✨Feat: 로그아웃 시에 헤더에서 알림 아이콘 숨김, 알림 삭제 버튼 모달창 적용
  src/components/common/Headers.vue
  src/components/common/Modal.vue
  src/pages/Notification.vue
Labels: enhancement
